### ISSUE TITLE
Support XcodeProjectPlugin

### ISSUE THREAD

**Issue by maiyama18** [maiyama18/LicensesPlugin#11]
I don't know if it's possible now, but it would be nice to support XcodeProjectPlugin.

An example of SwiftLint plugin is below.

https://github.com/realm/SwiftLint/blob/0bd8a7aba6555fa676c3442026f9b2ea90a70085/Plugins/SwiftLintPlugin/SwiftLintPlugin.swift#L60-L76

**Comment by moyerr** [comment]
@maiyama18 Was this implemented? I'm currently looking for solutions that can generate License info in Xcode projects that use SPM.
